### ISSUE TITLE
Criar um arquivo de estilo para utilizar no IntelliJ

### ISSUE THREAD

**Issue by agrava-luizalabs** [agrava-luizalabs/java-code-style#2]

**Comment by pecota-luizalabs** [comment]
Tá criado :)

**Comment by agrava-luizalabs** [comment]
The pull request #3 was closed because it was not fitting the requirements, a new one will be opened by @eduardomartins-luizalabs changing a few things

**Comment by pecota-luizalabs** [comment]
#4 created.
